name: Push test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        persist-credentials: true


    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        ssh: true
        branch: main
        repository: CSU-Index/CSU-Index.github.io
        force: true
