name: Push to Another Repository

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
 sync_latest_from_upstream:
   runs-on: ubuntu-latest
   name: Sync latest commits

   steps:
     - name: Checkout target repo
       uses: actions/checkout@v4
       with:
         persist-credentials: false

     - name: Upstream Sync
       id: sync
       uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
       with:
        target_sync_branch: main
        # REQUIRED 'target_repo_token' exactly like this!
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: main
        upstream_sync_repo: Temparo/csu-index
