name: repo-sync
on:
  schedule:
  - cron:  "0 18 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "Temparo/csu-index"
        source_branch: "main"
        destination_branch: "main"
        github_token: ${{ secrets.PAT }}
