name: Url process
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          cd url-process
          python "json-format-to-json.py"
          cd ..

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5

